APP=psoc6_head_adaptation

all: build

getlibs:
	@echo "[placeholder] ModusToolbox getlibs"

build:
	@echo "[placeholder] build firmware $(APP)"

program:
	@echo "[placeholder] flash firmware $(APP)"
